FROM oracle/graalvm-ce:19.3.1-java11 AS build-env
RUN gu install native-image
COPY .mvn/ ./.mvn
COPY mvnw .
COPY pom.xml .
RUN ./mvnw package --fail-never
COPY src src
RUN ./mvnw package -Pnative

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build-env target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]