####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the docker image run:
#
# mvn package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/exam-data-api-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/exam-data-api-jvm
#
###
FROM eclipse-temurin:11-jre-alpine
ENV TZ=America/Sao_Paulo \
    JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

WORKDIR /deployments

RUN addgroup -S appgroup && adduser -S appuser -G appgroup \
  && chown -R appuser:appgroup /deployments

COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar

EXPOSE 8080

USER appuser

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]